### ISSUE TITLE
Ознакомиться с темами по CSS

### ISSUE THREAD

**Issue by DimaKacer** [kli2m/PDP#3]
Дополнить свой PDP Следующими темами

### CSS

- Syntax, properties and capabilities etc.
- Special states and parts of elements
- Specificity, inheritance, cascade rules, selector attributes
- Weigh selectors
- Relative and Absolute Units (em, %, px, pt etc.)
- Block model and display
- Animation and Transformation
- Media Queries
- Web safe fonts, custom web fonts, font formats, icon fonts, font-face, font generators/services etc.
- Positioning
- Flex-box OR Grid layout
- Popular CSS Pre-processors (SASS/SCSS --or-- LESS)
- Responsive Web Design (RWD)
- Adaptive Web Design (AWD)
- Mobile approaches (mobile first, progressive enhancement, graceful degradation)

**Comment by kli2m** [comment]
Created PR  https://github.com/kli2m/PDP/pull/4
